const router = require('express').Router();
const { body } = require('express-validator');
const { getSettings, updateSettings } = require('../controllers/settingsController');
const { protect, admin } = require('../middlewares/auth');
const validate = require('../middlewares/validate');

router.get('/', getSettings);
router.put('/', protect, admin, [
  body('phones').optional().isArray(),
  body('phones.*.name').optional().isString().trim(),
  body('phones.*.tel').optional().isString().trim(),
  body('email').optional().isString().trim(),
  body('address').optional().isString().trim(),
  body('about').optional().isString().trim(),
  body('headerImage').optional().isString().trim(),
  body('shippingPrice').optional().isNumeric(),
  body('zarinpalMerchantId').optional().isString().trim(),
  body('zarinpal').optional().isObject(),
  body('zarinpal.enabled').optional().isBoolean(),
  body('cardToCard').optional().isObject(),
  body('cardToCard.active').optional().isBoolean(),
  body('cardToCard.bankName').optional().isString().trim(),
  body('cardToCard.cardNumber').optional().isString().trim(),
  body('cardToCard.accountHolder').optional().isString().trim(),
  body('festival').optional().isObject(),
  body('festival.active').optional().isBoolean(),
  body('festival.topBanner').optional().isBoolean(),
  body('festival.topBannerText').optional().isString().trim(),
  body('festival.title').optional().isString().trim(),
  body('festival.subtitle').optional().isString().trim(),
  body('festival.btnText').optional().isString().trim(),
  body('festival.bgColor').optional().isString().trim(),
  body('hidePrices').optional().isBoolean(),
  body('logo').optional().isString().trim(),
  body('favicon').optional().isString().trim(),
  body('siteName').optional().isString().trim(),
  body('heroTitle').optional().isString().trim(),
  body('heroSubtitle').optional().isString().trim(),
  body('distributor').optional().isObject(),
  body('distributor.active').optional().isBoolean(),
  body('distributor.title').optional().isString().trim(),
  body('distributor.brands').optional().isArray(),
  body('distributor.brands.*.name').optional().isString().trim(),
  body('distributor.brands.*.logo').optional().isString().trim(),
  body('socials').optional().isObject(),
  body('socials.telegram').optional().isObject(),
  body('socials.telegram.active').optional().isBoolean(),
  body('socials.telegram.link').optional().isString().trim(),
  body('socials.telegram.icon').optional().isString().trim(),
  body('socials.rubika').optional().isObject(),
  body('socials.rubika.active').optional().isBoolean(),
  body('socials.rubika.link').optional().isString().trim(),
  body('socials.rubika.icon').optional().isString().trim(),
  body('socials.bale').optional().isObject(),
  body('socials.bale.active').optional().isBoolean(),
  body('socials.bale.link').optional().isString().trim(),
  body('socials.bale.icon').optional().isString().trim(),
  validate,
], updateSettings);

module.exports = router;
